### ISSUE TITLE
thumbnail shrinks

### ISSUE THREAD

**Issue by balajisampathu** [Sriram-Ananth/EDGEPACS#10]
FIREFOX Browser : When we download the images, and scroll images on the thumbnail, the thumbnail shrinks.
![1](https://user-images.githubusercontent.com/62637925/77816463-c0f18a00-70e8-11ea-9a01-c45acad13ae8.JPG)

**Comment by Sriram-Ananth** [comment]
Issue fixed. Please check and revert
