### ISSUE TITLE
Worklist

### ISSUE THREAD

**Issue by balajisampathu** [Sriram-Ananth/EDGEPACS#12]
when we right click on the patient information, the study opens.  

![4](https://user-images.githubusercontent.com/62637925/77819173-bc37d080-70fe-11ea-9e41-120944c18fcf.JPG)

**Comment by Sriram-Ananth** [comment]
The context menu long press is now used only when running on a mobile or a tablet. On windows you can use double click

**Comment by Sriram-Ananth** [comment]
Been changed to long press now for touch devices and double click for desktop browsers
