### ISSUE TITLE
IPAD  - Need to relook at number of buttons

### ISSUE THREAD

**Issue by SathiWork** [Sriram-Ananth/EDGEPACS#18]
I tested with an 1080p IPAD tablet (landscape mode) using a Chrome browser, I found the last button peeking out. Newer tablets have higher resolutions may not have the same issue.

IPAD Resolutions:

IPAD 1st and 2nd Generation: 1024  x 768

IPAD 3rd Generation: 2048 x 1536

IPAD Pro 12.9": 2732 x 2048

We may need to decide which option to choose.

**Comment by Sriram-Ananth** [comment]
I am looking at creating a responsive toolbar. That will collapse into dropdown menus at smaller resolutions and possibly wrap into a second row at higher resolutions. Still WIP

**Comment by SathiWork** [comment]
Please note that due to the above resolution issues, x - windows close button is not visible in iPad

**Comment by SathiWork** [comment]
Closed it accidentally.

**Comment by Sriram-Ananth** [comment]
Does the current approach work Sathi? Shall I close this issue for now?

**Comment by SathiWork** [comment]
Yes, we can close this issue. I found a bug while using this, I will report this as a fresh bug. But, this approach works! :-)
