### ISSUE TITLE
IPAD: Suggestion for depressed buttons

### ISSUE THREAD

**Issue by SathiWork** [Sriram-Ananth/EDGEPACS#19]
Can we have depressed buttons to highlight which  functions is being used? As there is no hepatic or button push feel, we don't realize what mode has been selected.

**Comment by Sriram-Ananth** [comment]
Absolutely Sathi. Like I said the UI needs a lot of work. I dont have the down states for this button. Let me see if I can do some temporary jugaad

**Comment by SathiWork** [comment]
@Sriram-Ananth : I think you have closed this issue by displaying the activated button in B&W.
