### ISSUE TITLE
no save option in preferences - modality settings

### ISSUE THREAD

**Issue by balajisampathu** [Sriram-Ananth/EDGEPACS#23]
there is no save option in preferences - modality settings to save settings
![4](https://user-images.githubusercontent.com/62637925/78006142-3b751080-735a-11ea-9471-2c9be347bbd8.JPG)
.

**Comment by Sriram-Ananth** [comment]
This is not yet complete. WIP.

**Comment by Sriram-Ananth** [comment]
Completed now
