### ISSUE TITLE
Error while using extended buttons

### ISSUE THREAD

**Issue by SathiWork** [Sriram-Ananth/EDGEPACS#28]
Device: IPAD
Browser: Chrome

I press the extended menu option, the extended menu opens up work vertically as desired. There is no issue, when I try to use any of the menu options. However, an error event gets thrown up, if I try to touch any area, outside the horizontal menu.
![FC845AE7-4CA5-4C71-9BFF-3EFA714A7735](https://user-images.githubusercontent.com/62637807/78358049-27d2df80-75d0-11ea-9abe-aae0e333678c.png)

May you can catch this event, exit out of the Horizontal menu and refresh the screen.\

**Comment by Sriram-Ananth** [comment]
This is a debug message which I forgot to comment out.
