### ISSUE TITLE
Windowing issue

### ISSUE THREAD

**Issue by balajisampathu** [Sriram-Ananth/EDGEPACS#3]
if we use 1X2 layout and do window level and width, it applies on both the series.

![2](https://user-images.githubusercontent.com/62637925/77509901-9e1a6800-6e93-11ea-8bea-58e5e9495217.jpg)

**Comment by Sriram-Ananth** [comment]
This is true irrespective of the layout. All viewports will have the WC and WL applied to it. @

**Comment by balajisampathu** [comment]
is this not bug sriram

**Comment by Sriram-Ananth** [comment]
Dont think so. Just syncing. Again would like suggestions from everyone

**Comment by balajisampathu** [comment]
within the same series is fine but on the other series why should it apply

**Comment by Sriram-Ananth** [comment]
For now I have changed it so it only applies to the selected viewport. We will revisit this later.
