### ISSUE TITLE
Multi frame issue

### ISSUE THREAD

**Issue by balajisampathu** [Sriram-Ananth/EDGEPACS#32]
Once we download the Ultrasound series, if the first image is a multiframe image, it will play the cine loop. if we want to go to the next image, it does not allow to go to the next image.

**Comment by Sriram-Ananth** [comment]
Have changed the logic to not load any multiframes unless the user clicks on the thumbnail. If a series has both SF and MF images when the SF images will load. Else the viewport will stay blank.
