### ISSUE TITLE
Context Menu not set for MF playback menu

### ISSUE THREAD

**Issue by SathiWork** [Sriram-Ananth/EDGEPACS#33]
minor issue: Context help  is not setup for MF playback menu.

**Comment by SathiWork** [comment]
another minor issue: Context help not setup for play and pause/stop buttons

**Comment by Sriram-Ananth** [comment]
Are you referring to button hints when you hover over them? If so, I have added the hints now.

**Comment by SathiWork** [comment]
Yes @Sriram-Ananth. Thanks :-)
