### ISSUE TITLE
HP menu is empty

### ISSUE THREAD

**Issue by SathiWork** [Sriram-Ananth/EDGEPACS#34]
Device: IPAD
Browser: Chrome, Safari

HP Menu is empty and not working. It is working for the Layout menu.

![image](https://user-images.githubusercontent.com/62637807/78553283-9c9f5700-7826-11ea-9617-9a6c7b073ed9.png)

**Comment by SathiWork** [comment]
![EmptyHPMenu](https://user-images.githubusercontent.com/62637807/78553499-fd2e9400-7826-11ea-9d19-dc34a62b9ef9.png)

**Comment by SathiWork** [comment]
Device: Windows Tablet

Similarly, even in Windows Tablet mode, HP menu is empty; however, layout menu is working without any issue.

![image](https://user-images.githubusercontent.com/62637807/78557660-cf4d4d80-782e-11ea-8da7-6d7f78cd77b4.png)

**Comment by Sriram-Ananth** [comment]
This is not a bug. It simply means no protocols have been defined that matches the loaded study. It will load only those protocols that match the set criteria. In our server at this point no protocols are defined for MR
