### ISSUE TITLE
Unable to exit MF playback Menu

### ISSUE THREAD

**Issue by SathiWork** [Sriram-Ananth/EDGEPACS#35]
![unabletoExitMenu](https://user-images.githubusercontent.com/62637807/78553730-5b5b7700-7827-11ea-9a0f-1d861ede7d38.png)

Device Tested: IPAD
Browsers: All browsers

I am unable to exit out of MF playback menu. The only way to exit is to close the study. Can we have one more option : x-exit along with play, pause menu

**Comment by Sriram-Ananth** [comment]
The cine button is a toggle. Click on it again to close the cine toolbar
