### ISSUE TITLE
Set Default play rate to fps rate from DICOM settings

### ISSUE THREAD

**Issue by SathiWork** [Sriram-Ananth/EDGEPACS#36]
Suggested Enhancement: The current display frame rate is setup for 30 fps. Can we set this rate as per the 'Recommended rate at which the frames of a Multi-frame image should be displayed in frames/second' : DICOM tag 0008,2144). 

Suggested Enhancement: It would also be useful to display the total number of seconds captured  as described in the DICOM tag :'Total time in seconds that data was actually taken for the entire Multi-frame image.' --> (0018,0072)

**Comment by Sriram-Ananth** [comment]
I am currently using tag (0018. 1063) to find frame time. This is a type 1C tag whereas 0008, 2144 is a type 3 which is not required to be present. Please refer http://dicom.nema.org/medical/Dicom/2017e/output/chtml/part03/sect_C.7.6.5.html

**Comment by Sriram-Ananth** [comment]
For the 2nd recommendation, the user can add it as one of the overlay tags. Again its type 3 so may not exist.

**Comment by SathiWork** [comment]
Understood @Sriram-Ananth. Thank you for showing patience :-)
