### ISSUE TITLE
Alignment of Menus

### ISSUE THREAD

**Issue by SathiWork** [Sriram-Ananth/EDGEPACS#38]
![image](https://user-images.githubusercontent.com/62637807/78556572-d5dac580-782c-11ea-9975-7844fa55ab92.png)
Minor Issue: Can we align the menus?

**Comment by Sriram-Ananth** [comment]
Done. But on really small form factors like a phone the buttons will overlap. How should we deal with that?

**Comment by SathiWork** [comment]
I meant only for this screen or can we align this as part of 'settings and logout' menu.

**Comment by Sriram-Ananth** [comment]
This is what I meant Sathi.
![image](https://user-images.githubusercontent.com/53596330/78631278-973f1c80-78b9-11ea-9cc3-8caf096b64b7.png)

**Comment by SathiWork** [comment]
Ohh. Agreed. Let us leave that alone.
Some suggestions to use that space meaningful so that it does not stick out as bad design.
a) Can we display the login name or 
b)last login date & Time or 
c) number of minutes in current login
d) link to corporate website - Contact us page

You can close this after you read this.

**Comment by SathiWork** [comment]
Works on IPAD and windows tablet mode
