### ISSUE TITLE
Annotation tool

### ISSUE THREAD

**Issue by balajisampathu** [Sriram-Ananth/EDGEPACS#4]
when we use measurement tool and without pressing Esc button click on next series thumbnail, the measurement option starts on thumbnail

the above issue happens on most of the drawing tools like annotation, angle, rectangle, elliptical, cobb angle.

![3](https://user-images.githubusercontent.com/62637925/77510134-17b25600-6e94-11ea-831e-16d1f937bab2.jpg)

**Comment by Sriram-Ananth** [comment]
issue fixed. Please check
