### ISSUE TITLE
Logout does nothing

### ISSUE THREAD

**Issue by SathiWork** [Sriram-Ananth/EDGEPACS#40]
The logout does nothing - should put us back to login page. Maybe functionality not yet enabled.

Similarly, session logout should gracefully take us back to the login page.

**Comment by Sriram-Ananth** [comment]
No. This is a bug introduced in the latest version of the component set that we are using. Have already written to them about this.

**Comment by Sriram-Ananth** [comment]
Fixed. This fix will affect all dialogs. Including confirmations when saving and deleting all settings including presets, overlays, HPs etc
