### ISSUE TITLE
Unable to close the scout line

### ISSUE THREAD

**Issue by balajisampathu** [Sriram-Ananth/EDGEPACS#42]
once we choose select the scout line, there is no option to remove scout line.

**Comment by balajisampathu** [comment]
Hi Sriram,

Can you please replicate what is available in radion for scout line.
Also need option to select all the images in the series so that we can get all the lines for that series.

![image](https://user-images.githubusercontent.com/62637925/78965317-56920e00-7b1a-11ea-8a3b-68361922626f.png)

**Comment by Sriram-Ananth** [comment]
Please read my comment. This is not doable using the current toolkit. RADiON was using a different toolkit and this one is different. So please try and understand.
