### ISSUE TITLE
Extended menu not working first time

### ISSUE THREAD

**Issue by SathiWork** [Sriram-Ananth/EDGEPACS#44]
The extended menu is not seen in the first view but works always from second time.
![71B93F6B-76BF-4C4B-AE24-A2415779D637](https://user-images.githubusercontent.com/62637807/78747785-e2bffc00-7987-11ea-9f66-924aa8418b4b.png)
![CDAB057E-5023-4CDE-9D01-8ED65C121983](https://user-images.githubusercontent.com/62637807/78747794-e8b5dd00-7987-11ea-8dde-ff8b5ef64795.png)

**Comment by SathiWork** [comment]
Device Tested : IPAD, Windows tablet mode

**Comment by Sriram-Ananth** [comment]
This should be fixed now. Can you check and confirm?
