### ISSUE TITLE
Need close button on multiframe menu

### ISSUE THREAD

**Issue by SathiWork** [Sriram-Ananth/EDGEPACS#46]
While using windows tablet or in IPAD, it is inconvenient to go and click the extended menu to close the multiframe mode. 

![25A9CFD6-547C-468A-86A4-52236C4F8FAA](https://user-images.githubusercontent.com/62637807/78748572-fcfad980-7989-11ea-9084-2fd4ee22d636.png)

**Comment by Sriram-Ananth** [comment]
Added a close button
