### ISSUE TITLE
select icon

### ISSUE THREAD

**Issue by balajisampathu** [Sriram-Ananth/EDGEPACS#8]
once we move out of the view port, can you put the mouse select icon. when we move the mouse towards the thumbnail, it shows the scroll icon which is used in the view port
![1](https://user-images.githubusercontent.com/62637925/77554542-389e9980-6edc-11ea-9e93-847b89784a88.JPG)

**Comment by balajisampathu** [comment]
can you provide select icon for mouse when we press escape button or when we move the mouse on to the thumbnails.

**Comment by Sriram-Ananth** [comment]
In a desktop browser pressing ESC will revert to the stack state which is the default. In mobile or tablets guess you will need to click on the stack button to go to the default mode. Think the mouse cursor issue is also fixed.
